# Site
title: Matthew Albrecht
description: A software engineer with interests in 3d computer graphics, CAD design, and automation.
url: https://mattparks.net
logo: mattparks.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/background.png             # this image will be shown on post list page
  default-post: images/background.png   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# https://github.com/jekyll/jekyll/issues/3478#issuecomment-286181251
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Google Analytics
#google-analytics: UA-XXXXX-Y

# Social Links
email:              mattparks5855@gmail.com
#google.plus:       username
twitter:            mattparks_
#facebook:          username
github:             mattparks
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           matthew-albrecht
#xing:              username
#instagram:         username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .vscode, .sass-cache, .DS_Store]